apiVersion: v1
kind: Pod
metadata: 
  name: pod-1
  labels:
    purpose: affinty
spec: 
  containers: 
  #docker run -d --name nginx nginx
   - name: nginx
     image: nginx:stable-perl
---
apiVersion: v1
kind: Pod
metadata: 
  name: pod-2
spec: 
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - affinty
        topologyKey: topology.kubernetes.io/zone
  containers: 
  #docker run -d --name nginx nginx
   - name: nginx
     image: nginx:stable-perl